schema: '**/*.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
  reactApolloVersion: 3
  namingConvention:
    typeNames: pascal-case#pascalCase
    enumValues: upper-case#upperCase
  avoidOptionals: true #https://github.com/dotansimha/graphql-code-generator/issues/2314
  key: value
silent: false
